version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transaction_aggregator
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      TYPEORM_HOST: mysql
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: transaction_aggregator